-- ============================================================
-- V2: Java Entity 변경 사항 반영 (UUID -> Long 변경 및 스키마 동기화)
-- 데이터 타입 변경으로 인해 기존 테이블을 DROP하고 재생성
-- ============================================================

-- 1. 의존성 역순으로 기존 테이블 삭제 (UUID 기반 테이블 제거)
DROP TABLE IF EXISTS expenses;      -- 아직 엔티티 없지만 FK 때문에 삭제 필요
DROP TABLE IF EXISTS group_members;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS users;

-- 2. 시퀀스 생성 (Java의 @SequenceGenerator 설정과 일치시킴)
-- Group용 시퀀스 (allocationSize=10)
CREATE SEQUENCE IF NOT EXISTS groups_id_seq
    START WITH 1
    INCREMENT BY 10;

-- GroupMember용 시퀀스 (allocationSize=20)
CREATE SEQUENCE IF NOT EXISTS group_members_id_seq
    START WITH 1
    INCREMENT BY 20;


-- ============================================================
-- 3. Users 테이블 재생성
-- ============================================================
-- User.java: @GeneratedValue(strategy = GenerationType.IDENTITY)
-- BaseEntity 상속 안 함 -> created_at만 존재, updated_at 없음
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    bank_name VARCHAR(255),
    account_number VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ============================================================
-- 4. Groups 테이블 재생성
-- ============================================================
-- Group.java: BaseEntity 상속 -> created_at, updated_at 존재
-- Sequence 전략 사용
CREATE TABLE groups (
    id BIGINT NOT NULL DEFAULT nextval('groups_id_seq') PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(1000),
    creator_id BIGINT NOT NULL, -- UUID -> Long 변경
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT fk_groups_creator FOREIGN KEY (creator_id) REFERENCES users (id)
);

-- 인덱스 (Java: @Index(name="idx_creator_id", columnList="creator_id"))
CREATE INDEX idx_creator_id ON groups(creator_id);


-- ============================================================
-- 5. GroupMembers 테이블 재생성
-- ============================================================
-- GroupMember.java: BaseEntity 상속
-- Sequence 전략 사용, 별도의 PK(id) 존재
CREATE TABLE group_members (
    id BIGINT NOT NULL DEFAULT nextval('group_members_id_seq') PRIMARY KEY,
    user_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    role VARCHAR(255) NOT NULL, -- Enum (OWNER, MEMBER)
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT fk_gm_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_gm_group FOREIGN KEY (group_id) REFERENCES groups (id),

    -- 유니크 제약조건 (Java: @UniqueConstraint(name="uk_user_group"...))
    CONSTRAINT uk_user_group UNIQUE (user_id, group_id)
);

-- 인덱스 (Java: @Index 설정 반영)
CREATE INDEX idx_user_id ON group_members(user_id);
CREATE INDEX idx_group_id ON group_members(group_id);
CREATE INDEX idx_role ON group_members(role);