-- ============================================================
-- V3: 지출, 투표, 정산, 알림 기능 추가
-- ============================================================
-- 작성일: 2025-11-27
-- 설명: Expense, Vote, Settlement, Notification 관련 테이블 생성 및 기존 테이블 수정
-- ============================================================

-- ============================================================
-- 2. 기존 테이블 수정
-- ============================================================
-- Users 테이블: fcmToken, updated_at 컬럼 추가
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS fcm_token VARCHAR(255),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

-- Groups 테이블: invite_code 컬럼 추가
ALTER TABLE groups
    ADD COLUMN IF NOT EXISTS invite_code VARCHAR(8) UNIQUE NOT NULL DEFAULT '';

COMMENT ON COLUMN groups.invite_code IS '그룹 초대 코드 (8자리)';


-- ============================================================
-- 3. expenses 테이블 생성
-- ============================================================
CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    payer_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    amount BIGINT NOT NULL,
    expense_data TIMESTAMP NOT NULL, -- expenseData 필드명
    receipt_url VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT fk_expenses_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_expenses_payer FOREIGN KEY (payer_id) REFERENCES users (id)
);

CREATE INDEX idx_expenses_group ON expenses(group_id);
CREATE INDEX idx_expenses_payer ON expenses(payer_id);

COMMENT ON TABLE expenses IS '지출 내역';
COMMENT ON COLUMN expenses.expense_data IS '지출 발생 일시';


-- ============================================================
-- 4. ExpenseItem 테이블 생성
-- ============================================================
CREATE TABLE expense_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    price BIGINT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT fk_expense_items_expense FOREIGN KEY (expense_id) REFERENCES expenses (id) ON DELETE CASCADE
);

CREATE INDEX idx_expense_items_expense ON expense_items(expense_id);

COMMENT ON TABLE expense_items IS '지출 항목 (영수증의 개별 품목)';


-- ============================================================
-- 5. ExpenseParticipant 테이블 생성 (복합키)
-- ============================================================
CREATE TABLE expense_participants (
    expense_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,

    PRIMARY KEY (expense_id, user_id),

    CONSTRAINT fk_expense_participants_expense FOREIGN KEY (expense_id) REFERENCES expenses (id) ON DELETE CASCADE,
    CONSTRAINT fk_expense_participants_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_expense_participants_user ON expense_participants(user_id);

COMMENT ON TABLE expense_participants IS '지출 참여자 (N:N 관계)';


-- ============================================================
-- 6. tags 테이블 생성
-- ============================================================
CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    group_id BIGINT NOT NULL,

    CONSTRAINT fk_tags_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT uk_group_id_tag_name UNIQUE (group_id, name)
);

CREATE INDEX idx_tags_group ON tags(group_id);

COMMENT ON TABLE tags IS '지출 태그 (그룹별)';


-- ============================================================
-- 7. expense_tags 조인 테이블 생성 (N:N)
-- ============================================================
CREATE TABLE expense_tags (
    expense_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,

    PRIMARY KEY (expense_id, tag_id),

    CONSTRAINT fk_expense_tags_expense FOREIGN KEY (expense_id) REFERENCES expenses (id) ON DELETE CASCADE,
    CONSTRAINT fk_expense_tags_tag FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE
);

CREATE INDEX idx_expense_tags_tag ON expense_tags(tag_id);

COMMENT ON TABLE expense_tags IS '지출-태그 매핑 테이블';


-- ============================================================
-- 8. votes 테이블 생성
-- ============================================================
CREATE TABLE votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id BIGINT NOT NULL,
    is_closed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT fk_votes_expense FOREIGN KEY (expense_id) REFERENCES expenses (id)
);

CREATE INDEX idx_votes_expense ON votes(expense_id);

COMMENT ON TABLE votes IS '항목별 정산 투표';
COMMENT ON COLUMN votes.is_closed IS '투표 마감 여부';


-- ============================================================
-- 9. vote_options 테이블 생성
-- ============================================================
CREATE TABLE vote_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vote_id BIGINT NOT NULL,
    expense_item_id BIGINT NOT NULL,

    CONSTRAINT fk_vote_options_vote FOREIGN KEY (vote_id) REFERENCES votes (id) ON DELETE CASCADE,
    CONSTRAINT fk_vote_options_expense_item FOREIGN KEY (expense_item_id) REFERENCES expense_items (id) ON DELETE CASCADE
);

CREATE INDEX idx_vote_options_vote ON vote_options(vote_id);
CREATE INDEX idx_vote_options_expense_item ON vote_options(expense_item_id);

COMMENT ON TABLE vote_options IS '투표 옵션 (각 지출 항목)';


-- ============================================================
-- 10. user_votes 테이블 생성
-- ============================================================
CREATE TABLE user_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    vote_option_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT fk_user_votes_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_votes_vote_option FOREIGN KEY (vote_option_id) REFERENCES vote_options (id) ON DELETE CASCADE
);

CREATE INDEX idx_user_votes_user ON user_votes(user_id);
CREATE INDEX idx_user_votes_vote_option ON user_votes(vote_option_id);

COMMENT ON TABLE user_votes IS '사용자 투표 내역';


-- ============================================================
-- 11. settlements 테이블 생성
-- ============================================================
CREATE TABLE settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id BIGINT NOT NULL,
    method VARCHAR(255) NOT NULL, -- Enum: N_BUN_1, DIRECT, PERCENT, ITEM
    status VARCHAR(255) NOT NULL DEFAULT 'PENDING', -- Enum: PENDING, COMPLETED
    deadline TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT fk_settlements_expense FOREIGN KEY (expense_id) REFERENCES expenses (id)
);

CREATE INDEX idx_settlements_expense ON settlements(expense_id);
CREATE INDEX idx_settlements_status ON settlements(status);

COMMENT ON TABLE settlements IS '정산 정보';
COMMENT ON COLUMN settlements.method IS '정산 방식: N_BUN_1(N빵), DIRECT(직접), PERCENT(비율), ITEM(항목별)';
COMMENT ON COLUMN settlements.status IS '정산 상태: PENDING(진행중), COMPLETED(완료)';


-- ============================================================
-- 12. settlement_details 테이블 생성
-- ============================================================
CREATE TABLE settlement_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_id BIGINT NOT NULL,
    debtor_id BIGINT NOT NULL, -- 돈을 보내야 하는 사람
    creditor_id BIGINT NOT NULL, -- 돈을 받아야 하는 사람
    amount BIGINT NOT NULL,
    is_sent BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT fk_settlement_details_settlement FOREIGN KEY (settlement_id) REFERENCES settlements (id) ON DELETE CASCADE,
    CONSTRAINT fk_settlement_details_debtor FOREIGN KEY (debtor_id) REFERENCES users (id),
    CONSTRAINT fk_settlement_details_creditor FOREIGN KEY (creditor_id) REFERENCES users (id)
);

CREATE INDEX idx_settlement_details_settlement ON settlement_details(settlement_id);
CREATE INDEX idx_settlement_details_debtor ON settlement_details(debtor_id);
CREATE INDEX idx_settlement_details_creditor ON settlement_details(creditor_id);

COMMENT ON TABLE settlement_details IS '정산 상세 내역 (누가 누구에게 얼마를 보내야 하는지)';
COMMENT ON COLUMN settlement_details.is_sent IS '송금 완료 여부';


-- ============================================================
-- 13. notifications 테이블 생성
-- ============================================================
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL, -- Enum: SETTLEMENT_REQUEST, SETTLEMENT_REMINDER, VOTE_CREATED, VOTE_CLOSE, EXPENSE_ADDED, GROUP_INVITE
    content TEXT NOT NULL,
    related_id BIGINT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,

    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_notifications_recipient ON notifications(recipient_id);
CREATE INDEX idx_notifications_is_read ON notifications(is_read);
CREATE INDEX idx_notifications_type ON notifications(type);

COMMENT ON TABLE notifications IS '푸시 알림';
COMMENT ON COLUMN notifications.type IS '알림 타입: SETTLEMENT_REQUEST, SETTLEMENT_REMINDER, VOTE_CREATED, VOTE_CLOSE, EXPENSE_ADDED, GROUP_INVITE';
COMMENT ON COLUMN notifications.related_id IS '관련 엔티티 ID (지출, 정산, 투표 등)';
