name: Backend CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'

permissions:
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission
        working-directory: ./backend
        run: chmod +x gradlew

      - name: Build
        working-directory: ./backend
        run: ./gradlew build -x test

      - name: Test
        working-directory: ./backend
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/test_db
          SPRING_DATASOURCE_USERNAME: test_user
          SPRING_DATASOURCE_PASSWORD: test_password
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Backend Test Results
          path: backend/build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Deploy to Railway (main branch push only)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          npm i -g @railway/cli
          railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}
          railway up --service jeongchongmu
