# .github/workflows/ci.yml
name: Spring Boot CI/CD
on:
  push:
    branches: [ "main", "develop" ] # main 브랜치 푸시 시 실행
  pull_request:
    branches: [ "main" ] # main 브랜치로 PR 생성 시 실행
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 코드
      uses: actions/checkout@v4

    - name: Java 21 설정
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'

    - name: Gradle 실행 권한 부여
      run: chmod +x ./gradlew

    - name: Gradle 빌드 및 테스트
      run: ./gradlew clean build
      env:
        SPRING_PROFILES_ACTIVE: test # 테스트 환경 프로필 활성화

    - name: 테스트 결과 업로드
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/test-results/

    # 배포 단계 (main 브랜치만)
    - name: Docker 이미지 빌드 및 푸시
      if: github.ref == 'refs/heads/main' # main 브랜치에만 배포
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker build -t ${{ secrets.DOCKER_USERNAME }}/jeongchongmu-backend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/jeongchongmu-backend:latest
